WSI_ROZW_ZIP='./igor matynia wsi lab2.zip'

zip_solution:
	@ if [ -f $(WSI_ROZW_ZIP) ]; then rm $(WSI_ROZW_ZIP); echo 'Deleting old file'; fi;
	@ zip $(WSI_ROZW_ZIP) -r *.png *.py './sprawozdanie.ipynb'
	@ echo 'done! uwu'
